using System;
using IDS.Portable.Common;
using IDS.Portable.LogicalDevice;
using OneControl.Devices.EchoBrakeControl;
using OneControl.Direct.IdsCanAccessoryBle.Connections;

namespace OneControl.Direct.IdsCanAccessoryBle.EchoBrakeControl
{
	public interface IEchoBrakeControlBleDeviceSource : ILogicalDeviceSourceDirectEchoBrakeControl, ILogicalDeviceSourceDirectConnection, ILogicalDeviceSourceDirect, ILogicalDeviceSource, ILogicalDeviceSourceConnection, IEchoBrakeControlCommandsWithLogicalDevice, IAccessoryBleDeviceSource<SensorConnectionEchoBrakeControl>, IAccessoryBleDeviceSource, ICommonDisposable, IDisposable, ILogicalDeviceSourceDirectIdsAccessory, ILogicalDeviceSourceDirectRename, ILogicalDeviceSourceDirectMetadata, IAccessoryBleDeviceSourceDevices<EchoBrakeControlBleDeviceDriver>
	{
	}
}
