using System.Collections.Generic;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;

namespace IDS.Portable.LogicalDevice
{
	public interface ILogicalDeviceCapabilityWithFeatures : ILogicalDeviceCapability, INotifyPropertyChanged
	{
		IReadOnlyList<LogicalDeviceCapabilityFeatureId> CapabilityFeaturesAll { get; }

		bool IsCapabilityFeatureEnabled(LogicalDeviceCapabilityFeatureId capabilityFeatureId);

		Task<IEnumerable<LogicalDeviceCapabilityFeatureId>> GetCapabilitiesSupportedByFirmwareAsync(ILogicalDeviceWithCapability<ILogicalDeviceCapabilityWithFeatures> logicalDevice, CancellationToken cancellationToken);

		Task<LogicalDeviceCapabilityFeatureStatusPending> SetCapabilityFeatureAsync(ILogicalDeviceWithCapability<ILogicalDeviceCapabilityWithFeatures> logicalDevice, LogicalDeviceCapabilityFeatureId capabilityFeatureId, string requiredSoftwarePartNumber, CancellationToken cancellationToken);

		Task<IEnumerable<LogicalDeviceCapabilityFeatureId>> GetCapabilitiesMandatoryByFirmwareAsync(ILogicalDeviceWithCapability<ILogicalDeviceCapabilityWithFeatures> logicalDevice, CancellationToken cancellationToken);

		Task<IEnumerable<LogicalDeviceCapabilityFeatureId>> GetCapabilitiesUserDisabledAsync(ILogicalDeviceWithCapability<ILogicalDeviceCapabilityWithFeatures> logicalDevice, CancellationToken cancellationToken);

		Task SetCapabilitiesUserDisabledAsync(ILogicalDeviceWithCapability<ILogicalDeviceCapabilityWithFeatures> logicalDevice, LogicalDeviceCapabilityFeatureId capabilityFeatureId, bool disable, CancellationToken cancellationToken);
	}
}
