using System.ComponentModel;

namespace IDS.Portable.LogicalDevice
{
	public enum PidUnits
	{
		[Description("")]
		Unknown,
		[Description("")]
		None,
		[Description("")]
		Quantity,
		[Description("°")]
		Degrees,
		[Description("V")]
		Volts,
		[Description("A")]
		Amps,
		[Description("A-Hours")]
		AmpHours,
		[Description("C")]
		Celsius,
		[Description("F")]
		Fahrenheit,
		[Description("")]
		DateTime,
		[Description("Hour(s)")]
		Hours,
		[Description("Minute(s)")]
		Minutes,
		[Description("Minute(s)")]
		MinutesAfterMidnight,
		[Description("Second(s)")]
		Seconds,
		[Description("Day(s)")]
		Days,
		[Description("Month(s)")]
		Months,
		[Description("Years")]
		Years,
		[Description("ms")]
		Milliseconds,
		[Description("")]
		Mac,
		[Description("")]
		MacHigh,
		[Description("")]
		MacLow,
		[Description("")]
		IpAddress,
		[Description("")]
		Rssi,
		[Description("Inches")]
		Inches,
		[Description("")]
		Dynamic,
		[Description("Device Id")]
		MonitorPanelDeviceId,
		[Description("Flags")]
		Flags,
		[Description("%")]
		PercentInteger,
		[Description("Mixed")]
		Mixed,
		[Description("Miles")]
		Miles
	}
}
