using System;

namespace IDS.Core.IDS_CAN
{
	[Flags]
	public enum ADAPTER_OPTIONS : uint
	{
		NONE = 0u,
		ENABLE_LOCAL_HOST = 1u,
		AUTO_READ_DEVICE_PID_LIST = 2u,
		AUTO_READ_DEVICE_SESSION_LIST = 4u,
		AUTO_READ_DEVICE_BLOCK_LIST = 8u,
		AUTO_READ_DEVICE_PART_NUMBER = 0x10u,
		AUTO_READ_DTC_COUNT = 0x20u
	}
}
