namespace OneControl.Direct.IdsCanAccessoryBle.TirePressureMonitor
{
	public delegate void UpdateTirePressureMonitorReachabilityEventHandler(TirePressureMonitorBleDeviceDriver tirePressureMonitorBle);
}
