namespace OneControl.Direct.MyRvLink
{
	public enum MyRvLinkEventType
	{
		Unknown = 0,
		GatewayInformation = 1,
		DeviceCommand = 2,
		DeviceOnlineStatus = 3,
		DeviceLockStatus = 4,
		RelayBasicLatchingStatusType1 = 5,
		RelayBasicLatchingStatusType2 = 6,
		RvStatus = 7,
		DimmableLightStatus = 8,
		RgbLightStatus = 9,
		GeneratorGenieStatus = 10,
		HvacStatus = 11,
		TankSensorStatus = 12,
		RelayHBridgeMomentaryStatusType1 = 13,
		RelayHBridgeMomentaryStatusType2 = 14,
		HourMeterStatus = 15,
		Leveler4DeviceStatus = 16,
		LevelerConsoleText = 17,
		Leveler1DeviceStatus = 18,
		Leveler3DeviceStatus = 19,
		Leveler5DeviceStatus = 20,
		AutoOperationProgressStatus = 21,
		DeviceSessionStatus = 26,
		TankSensorStatusV2 = 27,
		RealTimeClock = 32,
		CloudGatewayStatus = 33,
		TemperatureSensorStatus = 34,
		JaycoTbbStatus = 35,
		MonitorPanelStatus = 43,
		AccessoryGatewayStatus = 44,
		AwningSensorStatus = 47,
		BrakingSystemStatus = 48,
		BatteryMonitorStatus = 49,
		ReFlashBootloader = 50,
		DoorLockStatus = 51,
		DimmableLightExtendedStatus = 53,
		LevelerType5ExtendedStatus = 54,
		HostDebug = 102,
		Invalid = 255
	}
}
